# GitHub action to validate ./data/records.json

name: Validate data
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: # https://github.com/stefanzweifel/git-auto-commit-action#checkout-the-correct-branch
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: 'x64'
      - run: pip install -r requirements.txt
      - name: Validate
        run: |
          python -m miscore ./data/records.json --raise_error
